version: "2.0"
services:
  quizonline:
    build: quizonline/dockerfile/.
    image: quizonline:1.0
    container_name: quizonline
    restart: always
    ports:
      - "18080:8080"
    environment:
      - INIT_MEM=2048m
      - MAX_MEM=4096m
    volumes:
      - webapps_quizonline:/usr/local/tomcat
  
  shopmates:
    build: shopmates/dockerfile/.
    image: shopmates:1.0
    container_name: shopmates
    restart: always
    ports:
      - "18081:8080"
    environment:
      - INIT_MEM=2048m
      - MAX_MEM=4096m
    volumes:
      - webapps_shopmates:/usr/local/tomcat

volumes:
  webapps_quizonline:
    external: true
  webapps_shopmates:
    external: true